name: Android Test Automation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  android-tests:
    runs-on: ubuntu-latest  # Use Linux runner

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Android SDK
      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.android
            /usr/local/lib/android/sdk
          key: android-sdk-${{ runner.os }}-30
          restore-keys: |
            android-sdk-${{ runner.os }}-30

      # Install Android SDK Tools (including ADB)
      - name: Install Android SDK Tools
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'
          build-tools-version: '34.0.0'
          platform-version: '30'
          emulator-version: 'latest'
          system-images: 'system-images;android-30;google_apis;arm64-v8a'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Download APK from GitHub Release
      - name: Download APK
        run: |
          curl -L -o ./apps/app-release.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk

      # Set up Android Emulator
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a  # Use ARM64 architecture
          profile: pixel
          emulator-options: "-no-window -no-snapshot -gpu swiftshader_indirect -no-audio -no-boot-anim -no-accel"  # Disable hardware acceleration
          disable-animations: true
          emulator-boot-timeout: 1200  # Increase timeout to 20 minutes
          script: |
            echo "Waiting for emulator to boot..."
            adb wait-for-device
            echo "Emulator is ready!"
            DEVICE=$(adb devices | grep emulator | cut -f1)
            echo "Using device: $DEVICE"
            echo "Installing APK..."
            adb -s $DEVICE install ./apps/app-release.apk
            echo "Running tests..."
            npm run test:ci

      # Debug Emulator
      - name: Debug Emulator
        run: |
          echo "List of connected devices:"
          adb devices
          echo "Emulator logs:"
          cat ~/.android/avd/test.avd/logcat.log

      # Upload Allure Results
      - name: Upload Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results/
