name: Android Test Automation

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    paths:
      - '**'  # Trigger on any changes in the repository

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use Node.js 18 (or the version you need)
          cache: 'npm'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Set environment variables for BrowserStack
      - name: Set environment variables
        run: |
          echo "BROWSERSTACK_USERNAME=amromoussa_KdSLyl" >> $GITHUB_ENV
          echo "BROWSERSTACK_ACCESS_KEY=EKpQhuMmc4axaaDNcJqd" >> $GITHUB_ENV
          echo "APK_PATH=./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk" >> $GITHUB_ENV

      # Step 6: Download APK (if needed)
      - name: Download APK
        run: |
          mkdir -p apps
          curl -L -o ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk

      # Step 7: Run tests on BrowserStack
      - name: Run tests on BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ env.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ env.BROWSERSTACK_ACCESS_KEY }}
        run: |
          npm run test:ci

      # Step 8: Generate Allure report
      - name: Generate Allure report
        run: npm run generate-report

      # Step 9: Upload Allure report as an artifact
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          if-no-files-found: warn