name: Android E2E Tests Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-emulator-e2e-tests:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'

    # Step 3: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 4: Install Android SDK Command-line Tools
    - name: Install Android SDK Command-line Tools
      uses: android-actions/setup-android@v2

    # Step 5: Launch Android Emulator
    - name: Launch Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Pixel_4_API_30
        emulator-options: -no-window -no-audio -gpu swiftshader_indirect -no-boot-anim
        disable-animations: true
        force-avd-creation: true
        cores: 2
        avd-name: test
        emulator-boot-timeout: 600

    # Step 6: Download and Install APK
    - name: Download and Install APK
      run: |
        mkdir -p apps
        curl -L -o ./apps/app-release.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk
        adb wait-for-device
        adb install ./apps/app-release.apk

    # Step 7: Install and Start Appium Server
    - name: Install and Start Appium Server
      run: |
        npm install -g appium
        appium --base-path / --port 4723 &

    # Step 8: Run E2E Tests
    - name: Run E2E Tests
      env:
        DEVICE_NAME: "emulator-5554"
        APK_PATH: "./apps/app-release.apk"
        APPIUM_HOST: "localhost"
        APPIUM_PORT: "4723"
        APPIUM_PATH: "/"
      run: npm run test:ci

    # Step 9: Terminate Emulator
    - name: Terminate Emulator
      run: adb -s emulator-5554 emu kill