on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: null  # Run the job directly on the host machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: sudo apt-get install -y libgl1-mesa-glx

      - name: Setup Android Environment
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-30,system-images;android-30;google_apis;x86_64'
          accept-android-sdk-licenses: true

      - name: Create and Start Emulator
        run: |
          echo "no" | avdmanager create avd --force --name testAVD --package 'system-images;android-30;google_apis;x86_64' --device 'Pixel 5'
          emulator @testAVD -no-window -no-audio -no-boot-anim -no-snapshot -boot-timeout 500 -qemu -m 2048 -smp 2 &
          sleep 30  # Wait for emulator to start

      - name: Wait for Emulator
        run: |
          adb wait-for-device
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

      - name: List ADB Devices
        run: adb devices

      - name: Download and Install APK
        run: |
          mkdir -p apps
          curl -L -o ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk
          adb install -r ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk

      - name: Run E2E Tests
        run: |
          npm run start:appium &
          sleep 30  # Increased wait time for Appium to start
          npm run test:ci

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: allure-results
          if-no-files-found: warn