name: Environment Verification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print working directory
        run: pwd

      - name: List files in repository
        run: ls -la

      - name: Create and list logs directory
        run: |
          mkdir -p logs
          echo "Logs directory created"
          ls -la logs

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
        run: |
          echo "Setting up Node.js..."
          node -v
          npm -v

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
        run: |
          echo "Setting up JDK 17..."
          java -version

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'
          accept-android-sdk-licenses: true
        run: |
          echo "Setting up Android SDK..."
          sdkmanager --list

      - name: Enable KVM
        run: |
          echo "Enabling KVM..."
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          lsmod | grep kvm

      - name: Verify AVD
        run: |
          echo "Verifying AVD setup..."
          ls ~/.android/avd

      - name: Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs
