name: Android Emulator CI with WebDriverIO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK for Android tools
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Step 3: Set up Android SDK
    - name: Set up Android SDK
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        profile: Nexus_6
        avd-name: test
        emulator-options: "-no-window -no-audio"
        disable-animations: true
        script: adb devices

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        npm ci

    # Step 5: Download APK
    - name: Download APK
      run: |
        curl -L -o ./apps/app-release.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk

    # Step 6: Start Appium Server
    - name: Start Appium server
      run: |
        npm install -g appium@2
        appium --base-path /wd/hub &
        sleep 10 # Wait for Appium to start

    # Step 7: Install APK on emulator
    - name: Install APK on emulator
      run: |
        adb install ./apps/app-release.apk

    # Step 8: Run WebDriverIO tests
    - name: Run WebDriverIO tests
      run: |
        npx wdio run ./wdio.ci.conf.js
