name: Android Emulator Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'
          accept-android-sdk-licenses: true

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Cache AVD
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-30

      - name: Update SDK and clear cache
        run: |
          yes | sdkmanager --update
          yes | sdkmanager --uninstall "build-tools;35.0.0" "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64"
          yes | sdkmanager --install "build-tools;35.0.0" "platform-tools" "platforms;android-30" "system-images;android-30;google_apis;x86_64"

      - name: Run tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader -noaudio -no-boot-anim
          script: |
            set -e
            mkdir -p apps
            curl -L -o ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk
            adb install ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk

            # Wait for emulator to boot
            for i in {1..60}; do
              adb shell getprop sys.boot_completed | grep -q "1" && break
              echo "Waiting for emulator to boot... (attempt $i)"
              sleep 5
            done

            npm install -g appium@2 --quiet
            appium --base-path /wd/hub &

            # Wait for Appium to start
            for i in {1..30}; do
              if curl -s localhost:4723/wd/hub/status | grep -q "status"; then
                echo "Appium server started"
                break
              fi
              echo "Waiting for Appium server to start..."
              sleep 2
            done

            # Run tests
            npx wdio run ./wdio.ci.conf.js || { echo "Tests failed"; exit 1; }

            # Terminate Emulator
            adb emu kill
            pkill -f "emulator" || true