name: Android E2E Tests with ARM Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Install Android SDK Tools
      run: |
        echo "Installing Android SDK Tools..."
        yes | sdkmanager --install "platform-tools"  # Install adb and fastboot
        yes | sdkmanager --install "system-images;android-30;default;arm64-v8a"  # Use ARM system image
        yes | sdkmanager --install "emulator"
        echo "Adding Android SDK tools to PATH..."
        echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH

    - name: Create Android Virtual Device (AVD)
      run: |
        echo "Creating Android Virtual Device (AVD)..."
        echo "no" | avdmanager create avd --force \
          --name "test" \
          --package "system-images;android-30;default;arm64-v8a" \
          --device "pixel_4" \
          --tag "default" \
          --abi "arm64-v8a"

    - name: Start Emulator
      run: |
        echo "Starting emulator..."
        emulator -avd test -no-window -no-audio -gpu swiftshader -no-boot-anim &
        adb wait-for-device
        while [[ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]]; do
          sleep 5
          echo "Waiting for emulator to boot..."
        done
        echo "Emulator booted successfully!"

    - name: Install dependencies
      run: npm install

    - name: Download and install APK
      run: |
        mkdir -p apps
        curl -L -o ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk
        adb install ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk

    - name: Run E2E tests
      env:
        DEVICE_NAME: "emulator-5554"  # Use the emulator device ID
        APK_PATH: "./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk"
        APPIUM_HOST: "localhost"
        APPIUM_PORT: "4723"
        APPIUM_PATH: "/"
      run: npm run test:ci

    - name: Stop Emulator
      run: |
        adb -s emulator-5554 emu kill
