jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      JAVA_TOOL_OPTIONS: "--add-modules=jakarta.xml.bind"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          android-version: '30'
          components: |
            platform-tools
            platforms;android-30
            build-tools;30.0.3
            emulator
            system-images;android-30;google_apis;x86

      - name: List system images
        run: $ANDROID_HOME/tools/bin/sdkmanager --list | grep "system-images;android-30;google_apis;x86"

      - name: Create AVD
        run: |
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd --name testAVD --package 'system-images;android-30;google_apis;x86' --force

      - name: Start Emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd testAVD -no-audio -no-window &
          sleep 300

      - name: Wait for Device
        run: adb wait-for-device

      - name: List ADB Devices
        run: adb devices

      - name: Install Dependencies
        run: npm install

      - name: Download APK
        run: |
          curl -L -o app.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk

      - name: Install APK
        run: adb install -r app.apk

      - name: Run Tests
        run: npm run test:ci