name: Android E2E Tests (Fixed Appium Path)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-22.04

    services:
      appium:
        image: appium/appium:latest
        ports:
          - 4723:4723
        options: >-
          --health-cmd "curl -f http://localhost:4723/status || exit 1"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 5

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        android-tools-component: 'platform-tools,build-tools-30.0.3,android-30,google-apis'
        install-component: 'platform-tools,build-tools-30.0.3,android-30,google-apis,emulator,sys-img-arm64-google_apis-30'

    - name: Install dependencies
      run: npm install

    - name: Start Android Emulator and Run Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: arm64-v8a
        profile: pixel
        emulator-options: "-no-window -no-audio -no-boot-anim -no-snapshot -no-accel -boot-timeout 500"
        disable-animations: true
        force-avd-creation: true
        script: |
          echo "Waiting for emulator to boot..."
          adb wait-for-device
          while ! adb shell getprop sys.boot_completed | grep 1; do
            sleep 15
          done
          echo "Emulator booted successfully!"

          echo "Downloading and installing APK..."
          mkdir -p apps
          curl -L -o ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk
          if [ -f ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk ]; then
            adb wait-for-device
            adb install -r ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk
            if [ $? -eq 0 ]; then
              echo "APK installed successfully!"
            else
              echo "Failed to install APK!"
              exit 1
            fi
          else
            echo "APK download failed!"
            exit 1
          fi

          echo "Running E2E tests..."
          npm run test:ci

    - name: Verify ADB Connection
      run: |
        adb wait-for-device
        adb devices

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: allure-results