name: Android Emulator Setup Without Boot

on:
  push:
    branches:
      - main

jobs:
  android-emulator-setup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          target: google_apis
          ndk: false

      # Step 3: Install Emulator Package
      - name: Install Emulator
        run: |
          echo "Installing emulator package..."
          sdkmanager "emulator"

      # Step 4: Install System Image
      - name: Install System Image
        run: |
          echo "Installing required system image..."
          sdkmanager "system-images;android-30;google_apis;x86_64"

      # Step 5: Configure Emulator
      - name: Configure Emulator
        run: |
          echo "Creating AVD..."
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
          echo "Emulator downloaded and configured."

      # Step 6: Start Emulator
      - name: Start Emulator
        run: |
          echo "Starting Emulator..."
          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -no-snapshot -no-boot-anim &
          adb wait-for-device
          echo "Emulator started."

      # Step 7: Download APK
      - name: Download APK
        run: |
          mkdir -p apps
          curl -L -o ./apps/app-release.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk

      # Step 8: Install APK on Emulator
      - name: Install APK
        run: |
          echo "Installing APK..."
          adb install ./apps/app-release.apk

      # Step 9: Run Test Scripts
      - name: Run Tests
        run: npm test
