name: Android Emulator Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create log directory
        run: mkdir -p logs

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'
          accept-android-sdk-licenses: true
        run: |
          echo "Setting up Android SDK..." | tee logs/android_sdk_setup.log
          sdkmanager --list >> logs/android_sdk_setup.log
          echo "Android SDK setup completed" >> logs/android_sdk_setup.log
          cat logs/android_sdk_setup.log

      - name: Enable KVM
        run: |
          echo "Enabling KVM..." | tee logs/kvm_setup.log
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          echo "KVM enabled" >> logs/kvm_setup.log
          cat logs/kvm_setup.log

      - name: Verify setup
        run: |
          echo "Node.js version:" > logs/setup_verification.log
          node -v >> logs/setup_verification.log
          echo "Java version:" >> logs/setup_verification.log
          java -version >> logs/setup_verification.log
          cat logs/setup_verification.log

      - name: Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs
