name: Android Emulator Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create log directory
        run: mkdir -p logs

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
        run: |
          echo "Setting up Node.js..." | tee logs/nodejs_setup.log
          node -v >> logs/nodejs_setup.log
          npm -v >> logs/nodejs_setup.log
          echo "Node.js setup completed" >> logs/nodejs_setup.log
          cat logs/nodejs_setup.log

      - name: Install dependencies
        run: |
          echo "Installing dependencies..." | tee logs/dependencies_install.log
          npm ci >> logs/dependencies_install.log 2>&1
          echo "Dependencies installation completed" >> logs/dependencies_install.log
          cat logs/dependencies_install.log

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
        run: |
          echo "Setting up JDK 17..." | tee logs/jdk_setup.log
          java -version >> logs/jdk_setup.log
          echo "JDK setup completed" >> logs/jdk_setup.log
          cat logs/jdk_setup.log

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'
          accept-android-sdk-licenses: true
        run: |
          echo "Setting up Android SDK..." | tee logs/android_sdk_setup.log
          sdkmanager --list >> logs/android_sdk_setup.log
          echo "Android SDK setup completed" >> logs/android_sdk_setup.log
          cat logs/android_sdk_setup.log

      - name: Verify setup
        run: |
          echo "Verifying setup..." | tee logs/setup_verification.log
          node -v >> logs/setup_verification.log
          java -version >> logs/setup_verification.log
          sdkmanager --list >> logs/setup_verification.log
          cat logs/setup_verification.log

      - name: Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs
