name: Basic Environment Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify environment
        run: |
          echo "Checking environment..."
          echo "Node.js version:" && node -v || echo "Node.js not found"
          echo "npm version:" && npm -v || echo "npm not found"
          echo "Java version:" && java -version || echo "Java not found"
          echo "Done with basic environment check."
