name: Android App E2E Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-22.04

    services:
      appium:
        image: appium/appium
        ports:
          - 4723:4723
        options: >-
          --health-cmd "curl -f http://localhost:4723/wd/hub/status || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: Pixel_4_API_30
        emulator-options: "-no-boot-anim -no-snapshot"
        disable-animations: true
        force-avd-creation: true

    - name: Verify Emulator Boot
      run: adb shell getprop sys.boot_completed | grep 1

    - name: Download and Install APK
      run: |
        mkdir -p apps
        curl -L -o ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk
        adb install ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk

    - name: Run E2E Tests
      env:
        DEVICE_NAME: "emulator-5554"
        APK_PATH: "./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk"
        APPIUM_HOST: "localhost"
        APPIUM_PORT: "4723"
        APPIUM_PATH: "/"
      run: npx wdio wdio.ci.conf.js
