name: Android E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Install Android Emulator
        run: |
          android-sdk/cmdline-tools/latest/bin/sdkmanager --install 'emulator'
          android-sdk/cmdline-tools/latest/bin/sdkmanager --install 'system-images;android-30;google_apis;x86'

      - name: Create AVD
        run: |
          echo "no" | android-sdk/cmdline-tools/latest/bin/avdmanager create avd --name testAVD --package 'system-images;android-30;google_apis;x86' --force

      - name: Start Emulator
        run: |
          nohup android-sdk/emulator/emulator -avd testAVD -no-audio -no-window &
          sleep 300

      - name: Install Dependencies
        run: npm install

      - name: Download APK
        run: |
          curl -L -o app.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk

      - name: Install APK
        run: adb install -r app.apk

      - name: Run Tests
        run: npm run test:cia