name: Android E2E Tests with Docker Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: |
        npm config set fetch-retry-mintimeout 20000
        npm config set fetch-retry-maxtimeout 120000
        npm install

    - name: Start Docker Emulator
      run: |
        docker pull budtmo/docker-android:latest  # Use the latest tag
        docker run -d \
          --name android-emulator \
          -e DEVICE="Pixel 4" \
          -e ANDROID_VERSION=30 \
          -e APPIUM=true \
          -p 4723:4723 \  # Appium port
          -p 5554:5554 \  # ADB port
          budtmo/docker-android:latest  # Use the latest tag

    - name: Wait for Emulator to Boot
      run: |
        echo "Waiting for emulator to boot..."
        adb wait-for-device
        while [[ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]]; do
          sleep 5
          echo "Waiting for emulator to boot..."
        done
        echo "Emulator booted successfully!"

    - name: Download and install APK
      run: |
        mkdir -p apps
        curl -L -o ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk https://github.com/Amromoussa2211/client/releases/download/v1.0.0/app-release-v15-0.3.2-2024-12-25-18-13.apk
        adb install ./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk

    - name: Run E2E tests
      env:
        DEVICE_NAME: "emulator-5554"
        APK_PATH: "./apps/app-release-v15-0.3.2-2024-12-25-18-13.apk"
        APPIUM_HOST: "localhost"
        APPIUM_PORT: "4723"
        APPIUM_PATH: "/"
      run: npm run test:ci

    - name: Stop Docker Emulator
      run: |
        docker stop android-emulator
        docker rm android-emulator