name: Basic Diagnostic

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create log directory
        run: mkdir -p logs

      - name: Print working directory
        run: pwd

      - name: List files in repository
        run: ls -la

      - name: Create a test file
        run: echo "This is a test file" > logs/test_file.txt

      - name: List logs directory
        run: |
          echo "Listing contents of logs directory:"
          ls -la logs

      - name: Archive logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: logs
